apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  labels:
    app: demo
spec:
  storageClassName: nfs-server
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.61.141
    # Exported path of your NFS server
    path: "/anithing"

