apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  labels:
    app: db-demo
spec:
  storageClassName: nfs-server
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

